version: '3.8'

services:
  blog-assignment-123:
    image: arbianshkodra/images:blog-assignment-123-v1.0.0
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog-assignment-123.rule=Host(`blog-assignment-123-ey9yit.accelero.sh`)"
      - "traefik.http.routers.blog-assignment-123.entrypoints=websecure"
      - "traefik.http.routers.blog-assignment-123.tls=true"
      - "traefik.http.services.blog-assignment-123.loadbalancer.server.port=3000"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true